### PR TITLE
Fix #803: Global [GM] tag

### LINKED ISSUE #803: Add global "[GM]" tag
**Describe the bug**
When you got multi moderators (Authority GameMaster, Administrator or Root) onlines, they individually see theirs [GM] tag, but others logged characters see nothing.

**To Reproduce**
1. Log in game on the same map with 2 accounts with Authority set to **more** than 1

**Expected behavior**
Online characters on the map must see [GM] tag and violet color for the name.

**Screenshots**
On Bariheal window :
image
On Barikade window :
image
On Bari window :
image

### PR DESCRIPTION
**Pull request by Bari77**

### CODE REVIEW

File: src/NosCore.GameObject/ComponentEntities/Extensions/CharacterEntityExtension.cs [hunk 1]
```diff
@@ -247,7 +247,7 @@ public static InPacket GenerateIn(this ICharacterEntity visualEntity, string pre
                 Direction = visualEntity.Direction,
                 InCharacterSubPacket = new InCharacterSubPacket
                 {
-                    Authority = (byte)visualEntity.Authority, //todo change chickenapi to short
+                    Authority = visualEntity.Authority > AuthorityType.Administrator ? (byte)2 : (byte)visualEntity.Authority, //todo change chickenapi to short
```
Comment (0Lucifer0) [inline src/NosCore.GameObject/ComponentEntities/Extensions/CharacterEntityExtension.cs]: Codacy Issue found: [Complete the task associated to this 'TODO' comment.](https://app.codacy.com/app/NosCoreIO/NosCore/pullRequest?prid=4515499)

**Comment by 0Lucifer0** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/NosCore/NosCore/pullRequest?prid=4515499&bid=15213644)

File: src/NosCore.GameObject/ComponentEntities/Extensions/CharacterEntityExtension.cs (hunk 1 above)
Comment (Elendan) [reply src/NosCore.GameObject/ComponentEntities/Extensions/CharacterEntityExtension.cs]: Instead of casting '2' to a byte, better cast AuthorityType.GameMaster to a byte. Magic Nubers are not really wanted though

(Even though a new enum would be better, as it's only for visibility purposes, this shouldn't be an AuthorityType)
